name: docx_viewer
description: A Flutter package which allows you to view Docx/Doc document format for Android.
version: 0.1.1
author:
  name: Santosh Bhandari
  email: info@bhandari-santosh.com.np
homepage: https://github.com/santoshvandari/docx_viewer
repository: https://github.com/santoshvandari/docx_viewer
documentation: https://pub.dev/packages/docx_viewer
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  docx_to_text: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.docxview.docx_viewer
        pluginClass: DocxViewerPlugin
      ios:
        pluginClass: DocxViewerPlugin
