name: docx_viewer
description: A Flutter package which allows you to view Docx/Doc document format for Android.
version: 0.1.3
homepage: https://github.com/santoshvandari/docx_viewer
repository: https://github.com/santoshvandari/docx_viewer
documentation: https://pub.dev/packages/docx_viewer
environment:
  sdk: ^3.5.4
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  docx_to_text: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.docxview.docx_viewer
        pluginClass: DocxViewerPlugin
      ios:
        pluginClass: DocxViewerPlugin
